apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-deployment
  namespace: node-test-dev
  labels:
    app: node-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
      - name: node-web
        image: shai2426/node-test:4053178213-5-1
        ports:
        - containerPort: 8080