apiVersion: v1
kind: Service
metadata:
  name: node-web-service
  namespace: node-test-dev
  labels:
    app: node-web
spec:
  type: LoadBalancer
  selector:
    app: node-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080